// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDmKGLG_2NjdeJKyv7Vf3lmnVgs5o9zDc',
    appId: '1:747467552728:web:0f6c7e20af29699537a4ad',
    messagingSenderId: '747467552728',
    projectId: 'chatapp-webuilder',
    authDomain: 'chatapp-webuilder.firebaseapp.com',
    storageBucket: 'chatapp-webuilder.appspot.com',
    measurementId: 'G-PFHZFRPQE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDI5yvf_o0VCw4nmbbpWbhWmkR4w8B-HI',
    appId: '1:747467552728:android:35520db65f36216b37a4ad',
    messagingSenderId: '747467552728',
    projectId: 'chatapp-webuilder',
    storageBucket: 'chatapp-webuilder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFXVc20K-baBZz7OcRzo2oxHtgshRB8U',
    appId: '1:747467552728:ios:4e96a015ff99e2e937a4ad',
    messagingSenderId: '747467552728',
    projectId: 'chatapp-webuilder',
    storageBucket: 'chatapp-webuilder.appspot.com',
    iosClientId: '747467552728-vqibpj36ggn2u4vp294ver8padg1gpe0.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoFXVc20K-baBZz7OcRzo2oxHtgshRB8U',
    appId: '1:747467552728:ios:7182863f99498c4b37a4ad',
    messagingSenderId: '747467552728',
    projectId: 'chatapp-webuilder',
    storageBucket: 'chatapp-webuilder.appspot.com',
    iosClientId: '747467552728-gkgovdg902u52k62s4nlvapcbgc9a92g.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp.RunnerTests',
  );
}
